### ISSUE TITLE
custom icon have the preset color or gray

### ISSUE THREAD

**Issue by Tyskiep99** [niklashenning/pyqttoast#17]
Hello,
I noticed that when I use an icon, it always have the preset color. If I dont set a preset, as the information one is default the icons end up full gray.
Is there a way to have the icon displayed as the original icon?

**Comment by Tyskiep99** [comment]
Some investigation lead me to this line, 
https://github.com/niklashenning/pyqttoast/blob/master/src/pyqttoast/toast.py#L929C1-L929C45
which is always executed when assigning the icon.

**Comment by niklashenning** [comment]
When you set the icon, it will automatically be displayed in the icon color that's currently set. The color is set to gray by default and also gets changed when applying presets. If you want to display the icon in its original color, just set the icon color to the original color of the icon. For example, if the original icon color is black, you can use:

```toast.setIconColor(QColor('#000'))```

If you also want to use a preset, this line has to come after the one that applies the preset.

Or are you trying to set a custom icon that has different colors that you want to keep?

**Comment by Tyskiep99** [comment]
I am trying to add an icon from an image, which has many different color on it, for instance I tested it with the python logo

**Comment by niklashenning** [comment]
Ah, now I understand. Unfortunately, this is not possible in the current version, as it's not designed for icons with multiple colors. But now that I'm thinking about it, there's no good reason for that.

I'm going to fix/change this in an update, so you'll be able to set the icon color to None or something like that, and it will just show the original icon without recoloring it. It's probably going to take a few days until it is released, though.

**Comment by Tyskiep99** [comment]
Thank for the reply, no hurry, I was just wondering as I would not except icon to have their color overridden unless using the setIconColor directly. And thanks for even considering, I may try to submit a PR

**Comment by niklashenning** [comment]
This has now been released with version v1.3.2

After updating to this version, simply add the following line to display the original icon:
```
toast.setIconColor(None)
```

![image](https://github.com/user-attachments/assets/e78d6d9e-5f19-4aad-a59d-bf137981b839)
